In [1]:
import pandas as pd
import os
import pyprojroot, sys
from pyprojroot.criterion import has_file
sys.path.insert(0, str(pyprojroot.find_root(has_file("pyproject.toml"))))

from dotenv import load_dotenv,find_dotenv

# load_dotenv()

env_file_path = find_dotenv()
print("当前加载的 .env 文件路径:", env_file_path)
# 2. 加载该文件
load_dotenv(env_file_path, override=True)

当前加载的 .env 文件路径: /workspace/worker/kdwk/Chrono/genuis/mizar/.env

True

In [2]:
from lib.flp001 import load_signal_performance,to_html1

/workspace/worker/kdwk/Chrono/genuis/mizar
/workspace/worker/kdwk/Chrono/genuis/mizar/config/contract.toml

In [3]:
results = load_signal_performance(
    "/workspace/worker/kdwk/Chrono/genuis/mizar/records/ricso2/rbb/temp/model/113001/5/rl/composite"
)

In [4]:
results1 = results[['signal_method','signal_id','model','code','data_type','ann_sharpe','calmar','win_rate','pl_ratio','plot']]
results1

,signal_method,signal_id,model,code,data_type,ann_sharpe,calmar,win_rate,pl_ratio,plot
0,linear_threshold_signal,1204,ensemble,HC,测试集,0.34,0.56,0.5174,1.02,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
1,linear_threshold_signal,1204,ensemble,RB,测试集,0.84,1.78,0.5194,1.06,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
2,linear_threshold_signal,1204,seed_2026,HC,测试集,0.04,0.04,0.5232,1.00,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
3,linear_threshold_signal,1204,seed_2026,RB,测试集,1.59,3.20,0.5227,1.11,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
4,linear_threshold_signal,1204,seed_3407,HC,测试集,0.67,1.44,0.5134,1.05,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
5,linear_threshold_signal,1204,seed_3407,RB,测试集,0.59,1.18,0.5158,1.04,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
6,linear_threshold_signal,1204,seed_42,HC,测试集,0.48,0.79,0.5192,1.03,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
7,linear_threshold_signal,1204,seed_42,RB,测试集,0.86,1.62,0.5205,1.06,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
8,threshold_signal,1304,ensemble,HC,测试集,0.14,0.22,0.5214,1.01,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
9,threshold_signal,1304,ensemble,RB,测试集,0.50,0.90,0.5228,1.05,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
10,threshold_signal,1304,seed_2026,HC,测试集,-0.15,-0.19,0.5159,0.99,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
11,threshold_signal,1304,seed_2026,RB,测试集,1.79,4.67,0.5428,1.17,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
12,threshold_signal,1304,seed_3407,HC,测试集,0.65,1.20,0.5169,1.05,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
13,threshold_signal,1304,seed_3407,RB,测试集,0.19,0.22,0.5094,1.01,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
14,threshold_signal,1304,seed_42,HC,测试集,0.24,0.35,0.5255,1.02,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
15,threshold_signal,1304,seed_42,RB,测试集,0.79,1.45,0.5202,1.07,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...

In [5]:
results1 = to_html1(results=results1, u_name='plot', k_name=['signal_method','signal_id','model','code'])

In [6]:
results1