In [1]:
import pandas as pd
import os
import pyprojroot, sys
from pyprojroot.criterion import has_file
sys.path.insert(0, str(pyprojroot.find_root(has_file("pyproject.toml"))))

from dotenv import load_dotenv,find_dotenv

# load_dotenv()

env_file_path = find_dotenv()
print("当前加载的 .env 文件路径:", env_file_path)
# 2. 加载该文件
load_dotenv(env_file_path, override=True)

当前加载的 .env 文件路径: /workspace/worker/kdwk/Chrono/genuis/mizar/.env

True

In [2]:
from lib.flp001 import load_signal_performance,to_html1

/workspace/worker/kdwk/Chrono/genuis/mizar
/workspace/worker/kdwk/Chrono/genuis/mizar/config/contract.toml

In [3]:
results = load_signal_performance(
    "/workspace/worker/kdwk/Chrono/genuis/mizar/records/ricso2/rbb/temp/model/113001/5/rl/10002/holdout"
)

In [4]:
results['data_type']

0     测试集
1     测试集
2     测试集
3     测试集
4     测试集
5     测试集
6     测试集
7     测试集
8     测试集
9     测试集
10    测试集
11    测试集
12    测试集
13    测试集
14    测试集
15    测试集
Name: data_type, dtype: object

In [5]:
results1 = results[['signal_method','signal_id','model','code','data_type','ann_sharpe','calmar','win_rate','pl_ratio','plot']]
results1.to_csv("10002_test.csv",encoding="UTF-8")

In [6]:
results1 = to_html1(results=results1, u_name='plot', k_name=['signal_method','signal_id','model','code'])

In [9]:
results

,signal_method,signal_id,model,code,segment,data_type,avg_ret,total_ret,sharpe,ann_sharpe,...,calmar,win_rate,pl_ratio,ic_mean,icir,turnover,factor_ac,ret_ac,performance_file,plot
0,linear_signal,1101,ensemble,HC,obse,测试集,0.08,0.1195,0.01,0.97,...,1.21,0.5102,1.03,0.0533,0.1962,0.6188,0.3123,0.0146,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
1,linear_signal,1101,ensemble,RB,obse,测试集,0.16,0.2620,0.02,1.78,...,3.29,0.5155,1.06,0.0703,0.2592,0.6266,0.3013,0.0437,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
2,linear_signal,1101,seed_2026,HC,obse,测试集,0.05,0.0662,0.00,0.50,...,0.43,0.5022,1.02,0.0549,0.2041,0.5714,0.3070,0.0146,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
3,linear_signal,1101,seed_2026,RB,obse,测试集,0.05,0.0769,0.01,0.52,...,0.64,0.5061,1.02,0.0698,0.2589,0.5745,0.2929,0.0437,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
4,linear_signal,1101,seed_3407,HC,obse,测试集,0.10,0.1526,0.01,1.32,...,2.87,0.5075,1.04,0.0498,0.1814,0.5879,0.2960,0.0146,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,threshold_signal,1304,seed_2026,RB,optimi,参数寻优集,0.13,0.5544,0.03,2.90,...,7.07,0.5352,1.22,0.0538,0.2080,0.1993,0.1732,0.0375,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
172,threshold_signal,1304,seed_3407,HC,optimi,参数寻优集,0.01,0.0223,0.00,0.21,...,0.22,0.5082,1.03,0.0268,0.1001,0.0789,0.1178,0.0589,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
173,threshold_signal,1304,seed_3407,RB,optimi,参数寻优集,0.06,0.2330,0.02,2.16,...,4.23,0.5404,1.31,0.0445,0.1705,0.0782,0.1106,0.0375,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
174,threshold_signal,1304,seed_42,HC,optimi,参数寻优集,0.04,0.1470,0.01,0.77,...,0.95,0.5101,1.06,0.0426,0.1592,0.2053,0.1825,0.0589,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
175,threshold_signal,1304,seed_42,RB,optimi,参数寻优集,0.15,0.6707,0.03,2.92,...,7.87,0.5415,1.23,0.0635,0.2411,0.2174,0.1669,0.0375,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...