In [1]:
import pandas as pd
import pyprojroot, sys,os,argparse
from pyprojroot.criterion import has_file
root = pyprojroot.find_root(has_file("pyproject.toml"))
sys.path.insert(0, str(root))

from dotenv import load_dotenv,find_dotenv

# load_dotenv()

env_file_path = find_dotenv()
print("当前加载的 .env 文件路径:", env_file_path)
# 2. 加载该文件
load_dotenv(env_file_path, override=True)

当前加载的 .env 文件路径: /workspace/worker/kdwk/Chrono/genuis/mizar/.env

True

In [2]:
from kdutils.tactix import Tactix
from kdutils.macro import base_path
from lib.flp001 import load_signal_performance,to_html1

/workspace/worker/kdwk/Chrono/genuis/mizar
/workspace/worker/kdwk/Chrono/genuis/mizar/config/contract.toml

In [3]:
config_file = "rbb.yaml"
config_id = "nn_rbb_signal"

In [4]:
args = argparse.Namespace(
    config_file=str(root / "config" / "research" / config_file),
    config_id=config_id,
)

In [5]:
variant = Tactix().yaml(args)

load file:/workspace/worker/kdwk/Chrono/genuis/mizar/config/research/rbb.yaml
load nn_rbb_signal config from /workspace/worker/kdwk/Chrono/genuis/mizar/config/research/rbb.yaml success
args has no attribute method, add it
------------------------------
args has no attribute task_id, add it
------------------------------
args has no attribute instruments, add it
------------------------------
args has no attribute period, add it
------------------------------
args has no attribute trial_id, add it
------------------------------
args has no attribute form, add it
------------------------------

In [6]:
method = variant.method
instrument = variant.instruments
task_id = variant.task_id
period = variant.period
trial_id = variant.trial_id
types1 = "holdout" if  variant.form == "metrics" else "composite"
types2 = "test" if  variant.form == "metrics" else "val"

In [7]:
input_dirs = os.path.join(base_path, method, instrument, "temp", "model",
                          str(task_id), str(period), "rl", str(trial_id), types1)
results = load_signal_performance(input_dirs)
print(input_dirs)
# results = load_signal_performance(
#     "/workspace/worker/kdwk/Chrono/genuis/mizar/records/ricso2/rbb/temp/model/113001/5/rl/10002/holdout"
# )

/workspace/worker/kdwk/Chrono/genuis/mizar/records/ricso2/rbb/temp/model/113001/5/rl/10002/holdout

In [8]:
results['data_type']

0     测试集
1     测试集
2     测试集
3     测试集
4     测试集
5     测试集
6     测试集
7     测试集
8     测试集
9     测试集
10    测试集
11    测试集
12    测试集
13    测试集
14    测试集
15    测试集
Name: data_type, dtype: object

In [10]:
results1 = results[['signal_method','signal_id','model','code','data_type','ann_sharpe','calmar','win_rate','pl_ratio','turnover','plot']]
filename = os.path.join(input_dirs, "{}_{}.csv".format(trial_id, types1))
results1.to_csv(filename,encoding="UTF-8")
print(filename)

/workspace/worker/kdwk/Chrono/genuis/mizar/records/ricso2/rbb/temp/model/113001/5/rl/10002/holdout/10002_holdout.csv

In [11]:
results1 = to_html1(results=results1, u_name='plot', k_name=['signal_method','signal_id','model','code'])

In [11]:
results

,signal_method,signal_id,model,code,segment,data_type,avg_ret,total_ret,sharpe,ann_sharpe,...,calmar,win_rate,pl_ratio,ic_mean,icir,turnover,factor_ac,ret_ac,performance_file,plot
0,linear_signal,1103,ensemble,HC,trst,测试集,0.01,0.0144,0.00,0.39,...,0.48,0.5066,1.01,0.0531,0.1959,0.2575,0.3403,0.0960,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
1,linear_signal,1103,ensemble,RB,trst,测试集,0.04,0.0743,0.01,1.62,...,3.75,0.5156,1.06,0.0667,0.2464,0.2574,0.3306,0.1341,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
2,linear_signal,1103,seed_2026,HC,trst,测试集,0.01,0.0113,0.00,0.27,...,0.31,0.5064,1.01,0.0501,0.1831,0.2652,0.3440,0.0960,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
3,linear_signal,1103,seed_2026,RB,trst,测试集,0.04,0.0781,0.01,1.38,...,3.26,0.5117,1.05,0.0655,0.2405,0.2645,0.3330,0.1341,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
4,linear_signal,1103,seed_3407,HC,trst,测试集,0.00,0.0012,0.00,0.05,...,0.05,0.5081,1.00,0.0456,0.1694,0.2335,0.3161,0.0960,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
5,linear_signal,1103,seed_3407,RB,trst,测试集,0.03,0.0486,0.01,1.24,...,2.87,0.5153,1.04,0.0581,0.2157,0.2327,0.3023,0.1341,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
6,linear_signal,1103,seed_42,HC,trst,测试集,0.02,0.0323,0.01,0.72,...,1.22,0.5115,1.02,0.0562,0.2083,0.2937,0.3423,0.0960,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
7,linear_signal,1103,seed_42,RB,trst,测试集,0.05,0.0944,0.02,1.81,...,4.82,0.5171,1.06,0.0681,0.2534,0.2947,0.3362,0.1341,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
8,threshold_signal,1301,ensemble,HC,trst,测试集,0.05,0.0883,0.01,0.86,...,1.14,0.5131,1.03,0.0431,0.1599,0.6963,0.2670,0.0960,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
9,threshold_signal,1301,ensemble,RB,trst,测试集,0.11,0.2054,0.01,1.57,...,3.29,0.5239,1.06,inf,NaN,0.6956,0.2570,0.1341,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
10,threshold_signal,1301,seed_2026,HC,trst,测试集,0.04,0.0707,0.01,0.65,...,0.63,0.5089,1.02,inf,NaN,0.6176,0.2617,0.0960,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
11,threshold_signal,1301,seed_2026,RB,trst,测试集,0.13,0.2509,0.02,1.65,...,4.49,0.5175,1.06,NaN,NaN,0.6162,0.2555,0.1341,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
12,threshold_signal,1301,seed_3407,HC,trst,测试集,0.02,0.0281,0.00,0.32,...,0.39,0.5138,1.01,0.0344,0.1307,0.6779,0.2494,0.0960,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
13,threshold_signal,1301,seed_3407,RB,trst,测试集,0.12,0.2165,0.02,1.71,...,4.68,0.5251,1.06,0.0496,0.1867,0.6772,0.2454,0.1341,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
14,threshold_signal,1301,seed_42,HC,trst,测试集,0.02,0.0219,0.00,0.24,...,0.33,0.5098,1.01,-inf,NaN,0.6875,0.2809,0.0960,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...
15,threshold_signal,1301,seed_42,RB,trst,测试集,0.15,0.2828,0.02,2.05,...,6.47,0.5207,1.07,inf,NaN,0.6846,0.2814,0.1341,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...,/workspace/worker/kdwk/Chrono/genuis/mizar/rec...