In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
import pyprojroot, sys
from pyprojroot.criterion import has_file
sys.path.insert(0, str(pyprojroot.find_root(has_file("pyproject.toml"))))
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

/workspace/worker/pj/Chrono/genuis/mizar
/workspace/worker/pj/Chrono/genuis/mizar/config/contract.toml

In [2]:
method = 'ricso2'
task_id = '134001'
session = '20260401'
instruments = 'hcb'
period = 5
category = 1

In [3]:
results = load_data(method=method, task_id=task_id, instruments=instruments, 
          period=period, session=session, category=category)
results['name'] = results['name'].astype(int).astype(int)
results['abs_ic'] = np.abs(results['ic_mean'])
#results['abs_icir'] = np.abs(results['icir'])
results1 = results.dropna(subset=['ann_sharpe','calmar'])
results1[['abs_ic','ann_sharpe','calmar']].tail()

/workspace/worker/pj/Chrono/genuis/mizar/records/ricso2/hcb/rulex/134001/nxt1_ret_5h/20260401

    abs_ic  ann_sharpe  calmar
25  0.0846        2.18    2.01
26  0.0571        2.21    2.18
27  0.0613        1.97    2.07
28  0.1117        2.05    2.32
29  0.1110        1.87    2.18

In [4]:
# results[results.expression.isin(drafit_data.formula.tolist())].to_csv("rbb_drafit.csv")
results1['abs_ic'].median()

0.0809

In [5]:
### IC大于0.03  ## 夏普大于2.2  # 卡玛大于2.5
results = results[(results['abs_ic']>0.03) & (results['ann_sharpe']>2) & (
    results['calmar']>2.2)].reset_index(drop=True)

In [6]:
results

,name,expression,avg_ret,total_ret,sharpe,ann_sharpe,max_dd,calmar,win_rate,pl_ratio,ic_mean,icir,turnover,factor_ac,ret_ac,roll_win,resampling_win,holding_profit,category,abs_ic
0,10547773,"MMinDiff(90,SIGLOG10ABS(MQUANTILE(90,'iv012_1_...",0.14,1084.65,0.02,2.08,-10.60,2.35,None,None,0.0568,0.2135,0.4079,0.0045,-0.0006,15.0,5.0,nxt1_ret_5h,p,0.0568
1,10665425,"SIGLOG2ABS(SIGLOG2ABS(MMinDiff(120,SIGLOG2ABS(...",0.16,1525.63,0.02,2.25,-12.43,2.30,None,None,-0.0810,-0.3092,0.4323,0.5968,0.0027,15.0,5.0,nxt1_ret_5h,p,0.0810
2,10598969,"SIGLOGABS(MMinDiff(60,'dv002_2_3_1'))",0.16,1536.49,0.02,2.26,-12.61,2.27,None,None,-0.0713,-0.2710,0.4307,0.5684,-0.0010,15.0,5.0,nxt1_ret_5h,p,0.0713
3,10969563,"MRANK(120,MDIFF(5,SIGLOG2ABS('dv002_2_3_1')))",0.16,1498.53,0.02,2.22,-12.51,2.26,None,None,-0.0729,-0.2785,0.4303,0.0538,0.0028,15.0,5.0,nxt1_ret_5h,p,0.0729
4,10790409,"MPERCENT(120,MADiff(240,'dv002_2_3_1'))",0.16,1524.13,0.02,2.25,-11.90,2.40,None,None,-0.0679,-0.2585,0.4307,0.0554,0.0003,15.0,5.0,nxt1_ret_5h,p,0.0679
5,10732995,"MMinDiff(60,'dv002_2_3_1')",0.16,1536.49,0.02,2.26,-12.61,2.27,None,None,-0.0713,-0.2710,0.4307,0.5684,-0.0010,15.0,5.0,nxt1_ret_5h,p,0.0713
6,10944102,"MMinDiff(120,'dv002_2_3_1')",0.16,1529.51,0.02,2.25,-12.34,2.31,None,None,-0.0809,-0.3088,0.4322,0.5972,0.0026,15.0,5.0,nxt1_ret_5h,p,0.0809
7,10368557,"SIGLOG2ABS(MMinDiff(120,MDIFF(240,ASIN('dv002_...",0.16,1536.14,0.02,2.25,-12.49,2.29,None,None,-0.0809,-0.3089,0.4322,0.5971,0.0026,15.0,5.0,nxt1_ret_5h,p,0.0809
8,10326367,"MMinDiff(120,MDIFF(120,'dv002_2_3_1'))",0.16,1529.51,0.02,2.25,-12.34,2.31,None,None,-0.0809,-0.3088,0.4322,0.5972,0.0026,15.0,5.0,nxt1_ret_5h,p,0.0809
9,10980146,"SIGLOG2ABS(MRANK(60,SIGLOG10ABS('iv012_1_2_1')))",0.15,1127.49,0.02,2.16,-9.60,2.64,None,None,0.0495,0.1853,0.3902,0.0042,-0.0009,15.0,5.0,nxt1_ret_5h,p,0.0495
10,10094815,SIGLOG2ABS('oi034_5_10_1'),0.16,1560.96,0.02,2.05,-12.39,2.32,None,None,-0.1117,-0.4473,0.4076,0.4407,0.0094,15.0,5.0,nxt1_ret_5h,p,0.1117

In [7]:
results = results[['expression','name']]
session_name = "/{0}".format(session)  if category == 1 else "/d{0}".format(session)  
results['plot'] = (base_path + '/' + str(method) + '/' + instruments + '/rulex' + '/' + str(task_id) + "/nxt1_ret_{0}h".format(period) \
    + session_name + '/plot/' + + results['name'].astype(str) + '.png')
results = results[['expression','plot','name']].rename(columns={'name':'factor_id','expression':'formula'})
results['plot'] = results['plot'].apply(make_clickable)

In [8]:
results['plot'].head().loc[0]

'<a target="_blank" href="/workspace/worker/pj/Chrono/genuis/mizar/records/ricso2/hcb/rulex/134001/nxt1_ret_5h/20260401/plot/10547773.png">/workspace/worker/pj/Chrono/genuis/mizar/records/ricso2/hcb/rulex/134001/nxt1_ret_5h/20260401/plot/10547773.png</a>'

In [9]:
### IC大于 total ic 0.02
### MA: total ic 0.015 mean ic 0.02  夏普 1.7 卡玛2.2
to_html(results)

In [10]:
results1.sort_values(by=['icir'],ascending=False).max()

name                                                    10980146
expression        TANH(MQUANTILE(120,SIGLOG2ABS('dv002_2_3_1')))
avg_ret                                                     0.17
total_ret                                                1805.23
sharpe                                                      0.02
ann_sharpe                                                  2.31
max_dd                                                      -9.6
calmar                                                      2.64
win_rate                                                    None
pl_ratio                                                    None
ic_mean                                                   0.2331
icir                                                      0.9616
turnover                                                  0.4343
factor_ac                                                 0.9099
ret_ac                                                    0.0125
roll_win                                                    15.0
resampling_win                                               5.0
holding_profit                                       nxt1_ret_5h
category                                                       p
abs_ic                                                    0.2331
dtype: object