### 使用 三段式查看 绩效

In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
import pyprojroot, sys
from pyprojroot.criterion import has_file
sys.path.insert(0, str(pyprojroot.find_root(has_file("pyproject.toml"))))

from dotenv import load_dotenv
load_dotenv()

from lib.flp001 import *

/workspace/worker/pj/Chrono/genuis/mizar
/workspace/worker/pj/Chrono/genuis/mizar/config/contract.toml

In [2]:
method = 'ricso2'
task_id = '134001'
instruments = 'hcb'
period = 5
category='p'

In [3]:
draft_data = load_data4(method=method, task_id=task_id, 
                        instruments=instruments,period=period,
                        filename='cohort_pro.csv'
)

In [4]:
draft_data#.columns

,factor_id,formula,category,direction,source,split,ic_mean,ann_sharpe,calmar,max_dd,avg_ret,total_ret,win_rate,pl_ratio,turnover,factor_ac,plot
0,10598969,"SIGLOGABS(MMinDiff(60,'dv002_2_3_1'))",p,-1,20260401,train,-0.0759,2.32,2.55,-12.61,0.18,857.83,None,None,0.4301,0.5347,/workspace/worker/pj/Chrono/genuis/mizar/recor...
1,10598969,"SIGLOGABS(MMinDiff(60,'dv002_2_3_1'))",p,-1,20260401,val,-0.0597,2.17,2.71,-7.26,0.11,70.95,None,None,0.4321,0.1237,/workspace/worker/pj/Chrono/genuis/mizar/recor...
2,10598969,"SIGLOGABS(MMinDiff(60,'dv002_2_3_1'))",p,-1,20260401,recent,-0.0615,2.14,3.17,-7.26,0.13,133.58,None,None,0.4331,0.1446,/workspace/worker/pj/Chrono/genuis/mizar/recor...
3,10969563,"MRANK(120,MDIFF(5,SIGLOG2ABS('dv002_2_3_1')))",p,-1,20260401,train,-0.0785,2.33,2.60,-12.51,0.18,881.13,None,None,0.4299,0.0512,/workspace/worker/pj/Chrono/genuis/mizar/recor...
4,10969563,"MRANK(120,MDIFF(5,SIGLOG2ABS('dv002_2_3_1')))",p,-1,20260401,val,-0.0590,1.95,2.05,-8.64,0.10,63.00,None,None,0.4313,0.0605,/workspace/worker/pj/Chrono/genuis/mizar/recor...
5,10969563,"MRANK(120,MDIFF(5,SIGLOG2ABS('dv002_2_3_1')))",p,-1,20260401,recent,-0.0623,2.15,2.66,-8.64,0.12,133.44,None,None,0.4322,0.0552,/workspace/worker/pj/Chrono/genuis/mizar/recor...
6,10732995,"MMinDiff(60,'dv002_2_3_1')",p,1,20260401,train,-0.0759,2.32,2.55,-12.61,0.18,857.83,None,None,0.4301,0.5347,/workspace/worker/pj/Chrono/genuis/mizar/recor...
7,10732995,"MMinDiff(60,'dv002_2_3_1')",p,1,20260401,val,-0.0597,2.17,2.71,-7.26,0.11,70.95,None,None,0.4321,0.1237,/workspace/worker/pj/Chrono/genuis/mizar/recor...
8,10732995,"MMinDiff(60,'dv002_2_3_1')",p,1,20260401,recent,-0.0615,2.14,3.17,-7.26,0.13,133.58,None,None,0.4331,0.1446,/workspace/worker/pj/Chrono/genuis/mizar/recor...

In [5]:
to_html(convert_to_merged_summary(draft_data, overwrite=True))