In [1]:
import pandas as pd
import os
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
from lib.iux002 import load_programs

In [3]:
method = 'bicso2'
instruments = 'rbb'
period = 5
task_id = '113001'
session = '20260325'#'202510217'
category = 'gentic'#'eligible' 'valid'

In [4]:
programs_data = load_programs(method=method, instruments=instruments, period=period, 
            task_id=task_id, session=session, 
            category=category) #gentic
programs_data.head()

,name,formual,final_fitness
0,ultron_1057559850129808,"MPERCENT(240,MDEMA(15,'dv002_1_2_1'))",0.061563
1,ultron_1082706908254681,"WMA(5,'oi004_1_2_1')",0.060806
2,ultron_1018335506195012,"SIGLOG2ABS(MDEMA(5,'oi039_2_3_1'))",0.060500
3,ultron_1084949441503829,SIGLOG2ABS(SIGLOG10ABS('oi039_2_3_1')),0.059153
4,ultron_1069908586566576,"MDIFF(90,MDIFF(90,MDIFF(10,'oi039_2_3_1')))",0.059100

In [5]:
programs_data.shape

(574, 3)

In [39]:
import re
search_string = "MT3(90,DELTA"
escaped_string = re.escape(search_string)
programs_data['is_target'] = programs_data['formual'].str.contains(escaped_string, na=False)
sorted_df = programs_data[programs_data['is_target']]
sorted_df#.head()

,name,formual,final_fitness,is_target
96,ultron_1008894818466398,"MT3(90,DELTA(5,MT3(90,MMaxDiff(120,'twap'))))",0.035699,True
110,ultron_1075666076194511,"MT3(90,MSUM(30,MT3(90,DELTA(15,'smart_tick_in'))))",0.028393,True

In [5]:
load_programs(method=method, instruments=instruments, period=period, task_id=task_id,
              session=session, category='valid').loc[20]['formual']

"MA(5,MAPOSITIVE(120,MA(5,MQUANTILE(90,MA(5,MA(5,MA(5,MA(5,MQUANTILE(90,'twap')))))))))"