In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

In [2]:
method = 'ricso2'
task_id = '113001'
session = '20260507'
instruments = 'rbb'
period = 5
category = 1

In [3]:
results = load_data(method=method, task_id=task_id, instruments=instruments, 
          period=period, session=session, category=category)
results['name'] = results['name'].astype(int).astype(int)
results['abs_ic'] = np.abs(results['ic_mean'])
#results['abs_icir'] = np.abs(results['icir'])
results1 = results.dropna(subset=['ann_sharpe','calmar'])
results1[['abs_ic','ann_sharpe','calmar']].tail()

./records/ricso2/rbb/rulex/113001/nxt1_ret_5h/20260507

    abs_ic  ann_sharpe  calmar
9   0.0600        2.57    3.86
10  0.0904        2.42    2.94
11  0.1305        2.76    3.33
12  0.0927        2.46    3.30
13  0.1164        2.82    3.82

In [4]:
# results[results.expression.isin(drafit_data.formula.tolist())].to_csv("rbb_drafit.csv")
results1['abs_ic'].median()

0.12345

In [5]:
### IC大于0.03  ## 夏普大于2.2  # 卡玛大于2.5
results = results[(results['abs_ic']>0.03) & (results['ann_sharpe']>2) & (
    results['calmar']>2.2)].reset_index(drop=True)

In [6]:
results

,name,expression,avg_ret,total_ret,sharpe,ann_sharpe,max_dd,calmar,win_rate,pl_ratio,ic_mean,icir,turnover,factor_ac,ret_ac,roll_win,resampling_win,holding_profit,category,abs_ic
0,10047868,"MDIFF(60,MIR(10,'tc012_1_1_2_1'))",0.20,5558.68,0.03,2.76,-10.61,3.33,None,None,-0.1305,-0.5391,0.4147,0.4925,-0.0381,15.0,5.0,nxt1_ret_5h,p,0.1305
1,10274744,"MDEMA(60,'tv005_2_3_0')",0.18,3371.60,0.02,2.36,-12.03,2.54,None,None,-0.1609,-0.6648,0.4064,0.7785,-0.0594,15.0,5.0,nxt1_ret_5h,p,0.1609
2,10697479,"MSUM(5,MADiff(90,MADiff(90,'iv005_1_2_0')))",0.20,5413.65,0.03,2.58,-13.04,2.69,None,None,-0.0517,-0.1996,0.4586,0.8258,-0.0594,15.0,5.0,nxt1_ret_5h,p,0.0517
3,10113351,"WMA(30,'tc012_1_1_2_0')",0.22,7165.12,0.03,2.89,-13.72,2.76,None,None,-0.2143,-0.9299,0.3831,0.7568,-0.0380,15.0,5.0,nxt1_ret_5h,p,0.2143
4,10256875,SIGLOG2ABS(SIGLOG2ABS(SIGLOG2ABS('tc004_2_2_3_...,0.15,1669.91,0.02,2.37,-9.00,2.67,None,None,-0.0878,-0.3428,0.4013,0.0090,0.0041,15.0,5.0,nxt1_ret_5h,p,0.0878
5,10566435,"MIR(10,'tc012_1_1_2_1')",0.20,5558.68,0.03,2.76,-10.61,3.33,None,None,-0.1305,-0.5391,0.4147,0.4925,-0.0381,15.0,5.0,nxt1_ret_5h,p,0.1305
6,10714483,"DELTA(5,'tc018_1_2_1')",0.21,6460.37,0.03,2.99,-9.44,3.91,None,None,-0.1138,-0.4603,0.4655,0.0971,-0.0381,15.0,5.0,nxt1_ret_5h,p,0.1138
7,10644330,"MDPO(120,RSI(10,MDPO(120,'tf020_1_2_1')))",0.19,4055.12,0.02,2.57,-8.36,3.86,None,None,-0.0600,-0.2348,0.4161,0.4704,-0.0589,15.0,5.0,nxt1_ret_5h,p,0.0600
8,10171457,SIGLOG2ABS(SIGLOG2ABS('tc004_2_2_3_0')),0.16,1833.22,0.02,2.42,-8.45,2.94,None,None,-0.0904,-0.3534,0.4026,0.0151,0.0041,15.0,5.0,nxt1_ret_5h,p,0.0904
9,10964248,"MIR(10,MDIFF(60,'tc012_1_1_2_1'))",0.20,5558.68,0.03,2.76,-10.61,3.33,None,None,-0.1305,-0.5391,0.4147,0.4925,-0.0381,15.0,5.0,nxt1_ret_5h,p,0.1305
10,10586006,SIGLOG2ABS('tc004_2_2_3_0'),0.16,1985.60,0.02,2.46,-7.77,3.30,None,None,-0.0927,-0.3636,0.4017,0.0233,0.0041,15.0,5.0,nxt1_ret_5h,p,0.0927
11,10156236,TANH('iv012_2_3_1'),0.20,5154.70,0.03,2.82,-9.07,3.82,None,None,0.1164,0.4565,0.4320,0.1465,-0.0378,15.0,5.0,nxt1_ret_5h,p,0.1164

In [7]:
results = results[['expression','name']]
session_name = "/{0}".format(session)  if category == 1 else "/d{0}".format(session)  
results['plot'] = (base_path + '/' + str(method) + '/' + instruments + '/rulex' + '/' + str(task_id) + "/nxt1_ret_{0}h".format(period) \
    + session_name + '/plot/' + + results['name'].astype(str) + '.png')
results = results[['expression','plot','name']].rename(columns={'name':'factor_id','expression':'formula'})
results['plot'] = results['plot'].apply(make_clickable)

In [8]:
results['plot'].head().loc[0]

'<a target="_blank" href="./records/ricso2/rbb/rulex/113001/nxt1_ret_5h/20260507/plot/10047868.png">./records/ricso2/rbb/rulex/113001/nxt1_ret_5h/20260507/plot/10047868.png</a>'

In [9]:
### IC大于 total ic 0.02
### MA: total ic 0.015 mean ic 0.02  夏普 1.7 卡玛2.2
to_html(results)

In [10]:
results1.sort_values(by=['icir'],ascending=False).max()

name                                    10989681
expression        WMA(5,MDIFF(15,'tv007_1_2_1'))
avg_ret                                     0.24
total_ret                                10297.2
sharpe                                      0.03
ann_sharpe                                  3.11
max_dd                                     -7.23
calmar                                      5.25
win_rate                                    None
pl_ratio                                    None
ic_mean                                   0.2674
icir                                      1.1232
turnover                                  0.4571
factor_ac                                 0.9686
ret_ac                                      0.01
roll_win                                    15.0
resampling_win                               5.0
holding_profit                       nxt1_ret_5h
category                                       p
abs_ic                                    0.2674
abs_icir                                  1.1232
dtype: object