In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

In [2]:
method = 'ricso2'
task_id = '113001'
session = '20260325'
instruments = 'rbb'
period = 5

In [3]:
results = load_data(method=method, task_id=task_id, instruments=instruments, 
          period=period, session=session, category=2)
results['name'] = results['name'].astype(int).astype(int)
results['abs_ic'] = np.abs(results['ic_mean'])
results['abs_icir'] = np.abs(results['icir'])
results1 = results
results1.tail()

,name,expression,avg_ret,total_ret,sharpe,ann_sharpe,max_dd,calmar,win_rate,pl_ratio,...,icir,turnover,factor_ac,ret_ac,roll_win,resampling_win,holding_profit,category,abs_ic,abs_icir
93,10164328,"MDEMA(15,MDPO(90,'oi039_2_3_1'))",0.21,6076.70,0.02,2.65,-12.42,2.08,51.19,1.10,...,0.1849,0.4403,0.4347,-0.1009,None,None,None,d,0.0489,0.1849
94,10851056,"MA(10,'iv012_1_2_1')",0.22,6880.89,0.02,2.71,-10.61,2.52,51.69,1.10,...,0.2085,0.4224,0.5878,-0.0861,None,None,None,d,0.0555,0.2085
95,10856476,"MDIFF(120,MADiff(240,'db006_2_3_1'))",0.19,3955.04,0.02,2.30,-10.02,2.29,51.28,1.10,...,0.1511,0.4234,0.4609,-0.1027,None,None,None,d,0.0418,0.1511
96,10273729,"MADiff(30,WMA(5,'oi004_5_10_1'))",0.20,4450.49,0.02,2.24,-11.76,2.02,51.09,1.09,...,-0.1583,0.4207,0.5789,-0.0836,None,None,None,d,0.0418,0.1583
97,10181121,"MMaxDiff(60,MMinDiff(60,'dv002_5_10_1'))",0.21,4474.78,0.02,2.53,-10.94,2.17,51.25,1.10,...,-0.1033,0.4132,0.8365,-0.1037,None,None,None,d,0.0273,0.1033

In [4]:
# drafit_data = pd.read_csv("/workspace/worker/pj/Chrono/genuis/mizar/records/bicso2/rbb/rulex/113001/nxt1_ret_5h/draft.csv")
# drafit_data

In [5]:
# results[results.expression.isin(drafit_data.formula.tolist())].to_csv("rbb_drafit.csv")

In [6]:
### IC大于0.03  ## 夏普大于2.2  # 卡玛大于2.5
results = results[(results['abs_ic']>0.06) & (results['ann_sharpe']>2.0) & (
    results['calmar']>1.5)].reset_index(drop=True)

In [7]:
results = results[['expression','name']]
results['path'] = (base_path + '/' + str(method) + '/' + instruments + '/rulex' + '/' + str(task_id) + "/nxt1_ret_{0}h".format(period) \
    + "/d{0}".format(session) + '/plot/' + + results['name'].astype(str) + '.png')
                   
results['path'] = results['path'].apply(make_clickable)

In [8]:
### IC大于0.03  ## 夏普大于2.2  # 卡玛大于2.5
to_html(results)

In [8]:
results1.sort_values(by=['icir'],ascending=False).max()

name                                               10995411
expression        WMA(5,WMA(5,MMaxDiff(240,'dv002_2_3_1')))
avg_ret                                                0.25
total_ret                                          13352.32
sharpe                                                 0.03
ann_sharpe                                             3.16
max_dd                                                 -7.7
calmar                                                 3.42
win_rate                                              52.33
pl_ratio                                               1.13
ic_mean                                              0.0907
icir                                                 0.3391
turnover                                             0.4642
factor_ac                                            0.9826
ret_ac                                              -0.0224
roll_win                                               None
resampling_win                                         None
holding_profit                                         None
category                                                  d
abs_ic                                                  inf
abs_icir                                             0.3391
dtype: object