### 使用val + train 一部分近期3年数据，看看绩效

In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
from lumina.genetic.util import create_id
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

In [2]:
method = 'ricso2'
task_id = '113001'
instruments = 'rbb'
period = 5

In [5]:
draft_data = load_data2(method=method, task_id=task_id, instruments=instruments, 
          period=period, filename='chosen_pro.csv')
draft_data.sort_values(by=['ann_sharpe'],ascending=False)[['formula','ic_mean','ann_sharpe','calmar','pl_ratio']]

,formula,ic_mean,ann_sharpe,calmar,pl_ratio
3,"EMA(10,'tc008_1_2_0')",-0.0686,3.22,3.45,1.13
19,"MDPO(15,'close')",-0.0633,3.16,2.13,1.13
63,"MDIFF(15,MDIFF(120,MCPS(240,'oi039_5_10_1')))",-0.0623,3.14,2.70,1.12
74,"MCPS(240,'oi004_5_10_1')",0.0622,3.14,2.83,1.12
44,"MDIFF(15,MCPS(240,'oi004_5_10_1'))",0.0622,3.14,2.83,1.12
...,...,...,...,...,...
52,"MDEMA(120,'iv012_1_2_1')",0.0907,2.45,2.11,1.09
41,"SIGLOG10ABS(MDEMA(120,'iv012_1_2_1'))",0.0902,2.44,2.10,1.09
24,"WMA(30,'oi039_2_3_1')",0.0640,2.43,2.01,1.09
83,"MDIFF(90,WMA(30,'oi039_2_3_1'))",0.0640,2.43,2.01,1.09
53,"EMA(30,MDEMA(5,'iv012_2_3_1'))",0.0604,2.35,2.54,1.09

In [6]:
draft_data['plot'] = draft_data['plot'].apply(make_clickable)

In [7]:
# draft_data.to_csv("rbb1.csv",encoding="UTF-8")
draft_data = draft_data[(draft_data['pl_ratio']>= 1.1) & (draft_data['ann_sharpe'] >= 2.5) & (draft_data['calmar'] >= 2.5)]
# draft_data.to_csv("pro_rbb.csv",encoding="UTF-8")
draft_data.head()

,factor_id,formula,category,direction,source,ic_mean,ann_sharpe,calmar,max_dd,avg_ret,total_ret,win_rate,pl_ratio,turnover,factor_ac,plot
3,10544376,"EMA(10,'tc008_1_2_0')",d,-1,20260503,-0.0686,3.22,3.45,-8.67,0.24,10841.56,52.09,1.13,0.4229,0.4084,"<a target=""_blank"" href=""./records/ricso2/rbb/..."
7,10442478,"EMA(5,'tc004_1_1_2_0')",d,-1,20260503,-0.0643,2.81,2.85,-8.90,0.21,5684.32,51.94,1.12,0.4231,0.1797,"<a target=""_blank"" href=""./records/ricso2/rbb/..."
14,10918821,"ADDED('oi034_5_10_1',MDEMA(15,MMAX(15,'oi039_2...",d,-1,20260421,-0.0654,3.05,2.75,-10.99,0.24,11283.50,51.93,1.12,0.4246,0.6035,"<a target=""_blank"" href=""./records/ricso2/rbb/..."
21,10810157,"MDIFF(240,MDIFF(30,'oi039_5_10_1'))",d,1,20260401,0.0658,3.11,2.81,-10.83,0.25,11667.98,51.98,1.12,0.4248,0.6044,"<a target=""_blank"" href=""./records/ricso2/rbb/..."
22,10822775,"MADiff(240,MDIFF(15,'oi039_5_10_1'))",d,1,20260401,0.0626,2.95,2.89,-10.81,0.25,13115.73,51.88,1.12,0.4247,0.6001,"<a target=""_blank"" href=""./records/ricso2/rbb/..."

In [8]:
to_html(draft_data[['plot','direction','formula','source']])