### 使用val + train 一部分近期3年数据，看看绩效

In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
from lumina.genetic.util import create_id
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

In [2]:
method = 'bicso3'
task_id = '122001'
instruments = 'mab'
period = 15

In [3]:
draft_data = load_data3(method=method, task_id=task_id, instruments=instruments, 
          period=period, filename='draft1.csv')
draft_data.sort_values(by=['ann_sharpe'],ascending=False)[['formula','ic_mean','ann_sharpe','calmar','pl_ratio']]

,formula,ic_mean,ann_sharpe,calmar,pl_ratio
23,"FRAC(MPERCENT(30,'oi034_2_5_1'))",-0.0397,1.83,2.46,1.11
21,"MPERCENT(30,'oi034_2_5_1')",-0.0397,1.83,2.46,1.11
4,"EXP(MMaxDiff(60,EXP('cr042_1_3_1')))",-0.0442,1.80,2.57,1.12
17,"MDPO(90,MMinDiff(30,'cr042_2_5_1'))",-0.0390,1.78,1.83,1.11
32,"MPERCENT(120,MMaxDiff(240,MCPS(90,'cr042_2_5_1...",0.0412,1.77,2.01,1.11
25,"MPERCENT(120,MCPS(90,'cr042_2_5_1'))",0.0409,1.73,2.03,1.11
14,"EXP(EXP(MMaxDiff(60,'cr042_1_3_1')))",-0.0456,1.71,2.05,1.11
27,"MQUANTILE(15,'tv017_2_5_1')",-0.0371,1.68,2.97,1.12
18,EXP('cr042_1_3_1'),-0.0470,1.68,1.98,1.10
3,SQRT(EXP('cr042_1_3_1')),-0.0472,1.67,2.06,1.10
8,"MDPO(90,MMinDiff(30,MDPO(90,'cr042_2_5_1')))",-0.0385,1.66,1.77,1.10
2,"MDIFF(90,MRANK(30,'cr042_2_5_1'))",-0.0394,1.64,1.70,1.10
6,"MRANK(30,MDIFF(5,'cr042_2_5_1'))",-0.0394,1.64,1.70,1.10
10,"MRANK(30,MDIFF(90,'cr042_2_5_1'))",-0.0394,1.64,1.70,1.10
0,"MDIFF(5,'cr042_2_5_1')",-0.0656,1.63,1.69,1.10
11,"MDIFF(5,MDIFF(5,'cr042_2_5_1'))",-0.0656,1.63,1.69,1.10
20,"MCPS(240,MADiff(60,'ixy014_2_5_1'))",0.0478,1.62,1.77,1.10
15,SIGLOG2ABS(SIGLOG2ABS('ixy014_2_5_1')),-0.0601,1.60,1.85,1.10
12,"MDPO(90,MMaxDiff(60,MDPO(90,'cr042_2_5_1')))",-0.0408,1.60,1.72,1.10
1,"MCPS(240,'ixy015_1_3_1')",0.0551,1.57,1.89,1.10
16,SIGLOG2ABS('ixy014_2_5_1'),-0.0614,1.56,1.72,1.10
7,"MDPO(90,'cr042_2_5_1')",-0.0409,1.56,1.57,1.10
22,"MADiff(240,MQUANTILE(15,MADiff(240,'tn003_1_2_...",-0.0355,1.54,3.03,1.11
30,"MMaxDiff(240,MPERCENT(30,'tc014_1_2_5_1'))",-0.0390,1.51,1.76,1.11
26,"MCPS(240,MDIFF(30,MDIFF(30,'ixy014_2_5_1')))",0.0628,1.50,1.56,1.09
28,"MCPS(240,MDIFF(30,'ixy014_2_5_1'))",0.0628,1.50,1.56,1.09
29,"MPERCENT(90,'tv017_2_5_1')",-0.0400,1.47,1.85,1.10
31,"MQUANTILE(90,'tc012_1_2_5_1')",-0.0400,1.47,1.85,1.10
5,"MPERCENT(30,SIGLOGABS('tc005_2_3_5_1'))",-0.0318,1.44,1.55,1.09
33,"MMinDiff(60,MPERCENT(90,'oi037_2_5_1'))",-0.0405,1.41,1.74,1.09
19,"MQUANTILE(240,MQUANTILE(240,'oi039_2_5_1'))",0.0353,1.36,1.48,1.09
13,"MMaxDiff(90,MRANK(60,MDIFF(10,'tc003_2_5_1')))",-0.0296,1.36,1.72,1.09
24,"MPERCENT(90,MCPS(240,'ixy014_2_5_1'))",0.0351,1.36,1.27,1.08
9,"MCPS(240,MQUANTILE(15,EMA(5,'oi034_2_5_1')))",0.0309,1.29,1.70,1.08

In [4]:
draft_data['plot'] = draft_data['plot'].apply(make_clickable)

In [5]:
# draft_data.to_csv("rbb1.csv",encoding="UTF-8")
draft_data1 = draft_data[(draft_data['pl_ratio']>= 1.05) & (draft_data['ann_sharpe'] >= 1.5) & (draft_data['calmar'] >= 1.5)]
# draft_data.to_csv("pro_rbb.csv",encoding="UTF-8")
draft_data1.head()

,factor_id,formula,category,direction,source,ic_mean,ann_sharpe,calmar,max_dd,avg_ret,total_ret,win_rate,pl_ratio,turnover,factor_ac,plot
0,10873711,"MDIFF(5,'cr042_2_5_1')",d,-1,20260616,-0.0656,1.63,1.69,-13.89,0.40,92.03,51.95,1.10,0.4578,-0.0036,"<a target=""_blank"" href=""./records/bicso3/mab/..."
1,10570864,"MCPS(240,'ixy015_1_3_1')",d,1,20260616,0.0551,1.57,1.89,-12.19,0.39,90.17,51.81,1.10,0.4450,-0.0016,"<a target=""_blank"" href=""./records/bicso3/mab/..."
2,10784882,"MDIFF(90,MRANK(30,'cr042_2_5_1'))",d,-1,20260616,-0.0394,1.64,1.70,-12.21,0.38,79.11,51.55,1.10,0.4487,-0.0516,"<a target=""_blank"" href=""./records/bicso3/mab/..."
3,10832225,SQRT(EXP('cr042_1_3_1')),d,-1,20260616,-0.0472,1.67,2.06,-11.73,0.40,95.57,51.63,1.10,0.4183,0.0003,"<a target=""_blank"" href=""./records/bicso3/mab/..."
4,10708962,"EXP(MMaxDiff(60,EXP('cr042_1_3_1')))",d,-1,20260616,-0.0442,1.80,2.57,-10.91,0.46,115.07,51.73,1.12,0.4113,0.0023,"<a target=""_blank"" href=""./records/bicso3/mab/..."

In [6]:
to_html(draft_data[['plot','direction','formula','source']])