In [2]:
import pandas  as pd

In [3]:
csv_path1 = '/workspace/data/fut_tick/7050707549_-/2026/202606/20260601/SA609_20260601.csv'

In [4]:
pd.read_csv(csv_path1)

,TradingDay,InstrumentID,UpdateTime,UpdateMillisec,LastPrice,Volume,BidPrice1,BidVolume1,AskPrice1,AskVolume1,AveragePrice,Turnover,OpenInterest,UpperLimitPrice,LowerLimitPrice
0,20260529,SA609,20:55:00,0,1215.0,0,0.0,0,0.0,0,0.0,0.000000e+00,1107329.0,1308.0,1114.0
1,20260529,SA609,20:55:02,0,1215.0,0,0.0,0,0.0,0,0.0,0.000000e+00,1107329.0,1308.0,1114.0
2,20260529,SA609,20:55:05,0,1215.0,0,0.0,0,0.0,0,0.0,0.000000e+00,1107329.0,1308.0,1114.0
3,20260529,SA609,20:55:25,0,1215.0,0,0.0,0,0.0,0,0.0,0.000000e+00,1107329.0,1308.0,1114.0
4,20260529,SA609,20:55:28,0,1215.0,0,0.0,0,0.0,0,0.0,0.000000e+00,1107329.0,1308.0,1114.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39979,20260601,SA609,14:59:58,0,1221.0,952297,1220.0,353,1221.0,16,1223.0,1.164659e+09,1073498.0,1308.0,1114.0
39980,20260601,SA609,14:59:59,0,1221.0,952318,1220.0,339,1221.0,3,1223.0,1.164685e+09,1073493.0,1308.0,1114.0
39981,20260601,SA609,14:59:59,0,1221.0,952319,1220.0,338,1221.0,2,1223.0,1.164686e+09,1073493.0,1308.0,1114.0
39982,20260601,SA609,15:00:00,0,1221.0,952322,1220.0,338,1222.0,1666,1223.0,1.164690e+09,1073494.0,1308.0,1114.0
39983,20260601,SA609,15:00:00,0,1221.0,952322,1220.0,338,1222.0,1666,1223.0,1.164690e+09,1073494.0,1308.0,1114.0

In [5]:
csv_path2 = '/workspace/data/fut_tick/7050707549_-/2026/202606/20260601/rb2701_20260601.csv'

In [6]:
pd.read_csv(csv_path2)

,TradingDay,InstrumentID,UpdateTime,UpdateMillisec,LastPrice,Volume,BidPrice1,BidVolume1,AskPrice1,AskVolume1,AveragePrice,Turnover,OpenInterest,UpperLimitPrice,LowerLimitPrice
0,20260601,rb2701,20:59:00,500,3199.0,45,3191.0,9,3199.0,36,31990.000000,1439550.0,146057.0,3353.0,3034.0
1,20260601,rb2701,21:00:00,500,3199.0,45,3191.0,9,3198.0,358,31990.000000,1439550.0,146057.0,3353.0,3034.0
2,20260601,rb2701,21:00:01,0,3199.0,45,3192.0,1,3197.0,10,31990.000000,1439550.0,146057.0,3353.0,3034.0
3,20260601,rb2701,21:00:01,500,3199.0,45,3193.0,8,3195.0,1,31990.000000,1439550.0,146057.0,3353.0,3034.0
4,20260601,rb2701,21:00:02,0,3198.0,47,3194.0,5,3197.0,9,31989.574468,1503510.0,146056.0,3353.0,3034.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21557,20260601,rb2701,14:59:59,0,3212.0,24034,3210.0,110,3212.0,1,32100.382791,771500600.0,151112.0,3353.0,3034.0
21558,20260601,rb2701,14:59:59,500,3212.0,24034,3210.0,110,3212.0,1,32100.382791,771500600.0,151112.0,3353.0,3034.0
21559,20260601,rb2701,15:00:00,0,3212.0,24034,3210.0,110,3212.0,1,32100.382791,771500600.0,151112.0,3353.0,3034.0
21560,20260601,rb2701,15:00:00,500,3212.0,24034,3210.0,110,3212.0,1,32100.382791,771500600.0,151112.0,3353.0,3034.0
21561,20260601,rb2701,15:16:29,500,3212.0,24034,3210.0,110,3212.0,1,32100.382791,771500600.0,151112.0,3353.0,3034.0

In [21]:
csv_path3 = "/workspace/data/fut_tick/7050707549_-/2019/201910/20191015/rb1910_20191015.csv"

In [23]:
pd.read_csv(csv_path3)#.sort_values(by=['UpdateTime'])

,TradingDay,InstrumentID,UpdateTime,UpdateMillisec,LastPrice,Volume,BidPrice1,BidVolume1,AskPrice1,AskVolume1,AveragePrice,Turnover,OpenInterest,UpperLimitPrice,LowerLimitPrice
0,20191015,rb1910,20:59:00,500,3645.0,0,3600.0,30,3610.0,60,0.0000,0.0,30360,3837.0,3402.0
1,20191015,rb1910,21:00:00,500,3610.0,120,3600.0,30,3635.0,210,36100.0000,4332000.0,30360,3837.0,3402.0
2,20191015,rb1910,21:00:01,0,3610.0,120,3600.0,30,3635.0,210,36100.0000,4332000.0,30360,3837.0,3402.0
3,20191015,rb1910,21:00:18,500,3610.0,120,3600.0,30,3635.0,210,36100.0000,4332000.0,30360,3837.0,3402.0
4,20191015,rb1910,21:00:28,500,3610.0,120,3600.0,30,3635.0,210,36100.0000,4332000.0,30360,3837.0,3402.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,20191015,rb1910,14:59:13,0,3581.0,7200,3580.0,240,3650.0,150,36122.2500,260080200.0,27480,3837.0,3402.0
403,20191015,rb1910,14:59:20,0,3650.0,7260,3580.0,240,3650.0,120,36125.3719,262270200.0,27420,3837.0,3402.0
404,20191015,rb1910,14:59:27,0,3650.0,7260,3580.0,240,3649.0,30,36125.3719,262270200.0,27420,3837.0,3402.0
405,20191015,rb1910,15:00:00,500,3650.0,7260,3580.0,240,3649.0,30,36125.3719,262270200.0,27420,3837.0,3402.0
406,20191015,rb1910,15:23:03,500,3650.0,7260,3580.0,240,3649.0,30,36125.3719,262270200.0,27420,3837.0,3402.0