In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
from lumina.genetic.util import create_id
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

In [2]:
method = 'bicso2'
task_id = '113001'
instruments = 'rbb'
period = 5

In [3]:
draft_data = load_data2(method=method, task_id=task_id, instruments=instruments, 
          period=period)
draft_data.head()

,factor_id,formula,category,direction,source,ic_mean,ann_sharpe,calmar,max_dd,avg_ret,total_ret,win_rate,pl_ratio,turnover,factor_ac,plot
0,10115252,"MRes(240,MMinDiff(120,'tc004_10_10_15_1'),MDIF...",d,-1,20260325,-0.1577,2.87,3.32,-12.08,0.22,8308.77,52.07,1.11,0.4355,0.5464,./records/bicso2/rbb/rulex/113001/nxt1_ret_5h/...
1,10153064,"SIGLOG2ABS(MPERCENT(120,SIGLOG10ABS('oi039_2_3...",d,1,20260325,0.0899,2.81,3.38,-8.75,0.17,2923.43,52.43,1.11,0.4084,0.0207,./records/bicso2/rbb/rulex/113001/nxt1_ret_5h/...
2,10568718,"MRes(240,MA(240,'tc004_10_10_15_1'),'oi004_5_1...",d,-1,20260325,-0.1661,2.91,3.74,-10.95,0.23,8985.63,52.11,1.11,0.4310,0.5930,./records/bicso2/rbb/rulex/113001/nxt1_ret_5h/...
3,10392140,"MDIFF(90,MDIFF(15,MDIFF(90,'oi039_2_3_1')))",d,1,20260325,0.1178,2.93,3.80,-8.82,0.19,4370.88,52.12,1.12,0.4079,0.0759,./records/bicso2/rbb/rulex/113001/nxt1_ret_5h/...
4,10733688,"ASIN(ASIN(MDIFF(5,'oi004_5_10_1')))",d,-1,20260325,-0.1805,3.01,3.59,-11.74,0.23,10088.61,52.25,1.12,0.4312,0.5934,./records/bicso2/rbb/rulex/113001/nxt1_ret_5h/...

In [5]:
draft_data['plot'] = draft_data['plot'].apply(make_clickable)

In [24]:
# draft_data.to_csv("rbb1.csv",encoding="UTF-8")
draft_data = draft_data[(draft_data['pl_ratio']>= 1.1) & (draft_data['ann_sharpe'] >= 2.5) & (draft_data['calmar'] >= 3)]
draft_data.to_csv("pro_rbb.csv",encoding="UTF-8")

In [25]:
to_html(draft_data[['plot','direction','formula']])