In [1]:
import pandas  as pd
import numpy as np
import pdb, os, datetime, itertools, time, hashlib
from dotenv import load_dotenv

load_dotenv()
from lib.flp001 import *

In [2]:
method = 'bicso2'
task_id = '113001'
session = '20260421'
instruments = 'rbb'
period = 5

In [4]:
results = load_data(method=method, task_id=task_id, instruments=instruments, 
          period=period, session=session, category=2)
results['name'] = results['name'].astype(int).astype(int)
results['abs_ic'] = np.abs(results['ic_mean'])
results['abs_icir'] = np.abs(results['icir'])
results1 = results
results1.tail()

,name,expression,avg_ret,total_ret,sharpe,ann_sharpe,max_dd,calmar,win_rate,pl_ratio,...,icir,turnover,factor_ac,ret_ac,roll_win,resampling_win,holding_profit,category,abs_ic,abs_icir
77,10776332,"MRANK(120,MMaxDiff(90,'oi004_2_3_1'))",0.16,2417.47,0.02,2.51,-8.40,3.31,51.89,1.10,...,-0.1732,0.4110,0.4069,0.0268,None,None,None,d,0.0473,0.1732
78,10151575,"MDIFF(90,'ixy007_10_15_1')",0.22,8182.17,0.03,2.80,-12.00,3.33,52.22,1.10,...,-0.7457,0.4109,0.7334,0.0339,None,None,None,d,0.1786,0.7457
79,10522409,"ADDED('oi039_2_3_1',MRANK(240,MRANK(240,'oi039...",0.17,2947.25,0.03,2.77,-10.15,2.93,52.46,1.11,...,0.3651,0.4110,0.0365,0.0335,None,None,None,d,0.0934,0.3651
80,10630309,"MDEMA(5,SIGLOG10ABS(MDEMA(5,'iv012_2_3_1')))",0.18,3206.01,0.02,2.45,-11.42,2.67,51.76,1.10,...,0.3873,0.4781,-0.0455,0.0328,None,None,None,d,0.0971,0.3873
81,10538193,"MADiff(120,MMinDiff(240,'oi039_2_3_1'))",0.18,3604.33,0.03,2.73,-9.20,3.44,51.90,1.11,...,0.2955,0.4071,0.6506,0.0334,None,None,None,d,0.0784,0.2955

In [4]:
# drafit_data = pd.read_csv("/workspace/worker/pj/Chrono/genuis/mizar/records/bicso2/rbb/rulex/113001/nxt1_ret_5h/draft.csv")
# drafit_data

In [5]:
# results[results.expression.isin(drafit_data.formula.tolist())].to_csv("rbb_drafit.csv")

In [6]:
### IC大于0.03  ## 夏普大于2.2  # 卡玛大于2.5
results = results[(results['abs_ic']>0.03) & (results['ann_sharpe']>2.2) & (
    results['calmar']>2.8)].reset_index(drop=True)

In [7]:
results = results[['expression','name']]
results['path'] = (base_path + '/' + str(method) + '/' + instruments + '/rulex' + '/' + str(task_id) + "/nxt1_ret_{0}h".format(period) \
    + "/d{0}".format(session) + '/plot/' + + results['name'].astype(str) + '.png')
                   
results['path'] = results['path'].apply(make_clickable)

In [8]:
### IC大于0.03  ## 夏普大于2.2  # 卡玛大于2.5
to_html(results)

In [9]:
results1.sort_values(by=['icir'],ascending=False).max()

name                                    10995411
expression        WMA(90,MDPO(60,'oi004_2_3_1'))
avg_ret                                     0.24
total_ret                               12370.71
sharpe                                      0.03
ann_sharpe                                  3.19
max_dd                                     -6.95
calmar                                      4.77
win_rate                                   53.01
pl_ratio                                    1.13
ic_mean                                   0.2763
icir                                      1.1921
turnover                                  0.4879
factor_ac                                  0.976
ret_ac                                    0.0385
roll_win                                    None
resampling_win                              None
holding_profit                              None
category                                       d
abs_ic                                    0.2763
abs_icir                                  1.1921
dtype: object