In [1]:
import pandas as pd

In [2]:
factors_data = pd.read_feather("dt1.feather")

In [3]:
factor_data1 = factors_data[['trade_time','code',"MADecay(30,'oi039_1_2_1')"]]

In [4]:
factor_data1.set_index("trade_time").loc["2011-01-04 09:18:00":"2024-02-21 09:54:00"]

                    code  MADecay(30,'oi039_1_2_1')
trade_time
2011-01-04 09:18:00   RB                  -8.144343
2011-01-04 09:19:00   RB                  -8.144235
2011-01-04 09:20:00   RB                  -8.144129
2011-01-04 09:21:00   RB                  -8.144048
2011-01-04 09:22:00   RB                  -8.143958
...                  ...                        ...
2024-02-21 09:50:00   RB                  -8.525721
2024-02-21 09:51:00   RB                  -8.525875
2024-02-21 09:52:00   RB                  -8.526045
2024-02-21 09:53:00   RB                  -8.526203
2024-02-21 09:54:00   RB                  -8.526329

[1010073 rows x 2 columns]

In [5]:
dt3 = pd.read_feather("/workspace/worker/pj/Chrono/genuis/mizar/records/bicso2/rbb/factors/i012_factors.feather")

In [4]:
dt3[['trade_time','code','oi039_1_2_1']]

                 trade_time code  oi039_1_2_1
0       2011-01-04 09:00:00   RB    -0.002535
1       2011-01-04 09:01:00   RB    -0.001947
2       2011-01-04 09:02:00   RB    -0.000508
3       2011-01-04 09:03:00   RB     0.000383
4       2011-01-04 09:04:00   RB     0.000266
...                     ...  ...          ...
1122320 2025-06-27 22:56:00   RB     0.000290
1122321 2025-06-27 22:57:00   RB     0.000097
1122322 2025-06-27 22:58:00   RB     0.000253
1122323 2025-06-27 22:59:00   RB    -0.000357
1122324 2025-06-27 23:00:00   RB    -0.000340

[1122325 rows x 3 columns]

In [5]:
dt4 = pd.read_feather("/workspace/worker/pj/Chrono/genuis/mizar/records/bicso2/rbb/basic/train_data.feather")

In [8]:
dt41 = dt4[['trade_time','code','close', 'high', 'low', 'open', 'value','volume', 'openint', 'vwap']]

In [11]:
from lumina.impulse.fixed import *

In [13]:
dt51 = dt41.set_index(['trade_time','code'])

In [15]:
close = dt51['close'].unstack()
openint = dt51['openint'].unstack()

In [16]:
from lumina.impulse.fixed import *