In [1]:
import os
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
from kdutils.data import fetch_main_market, fetch_local_market, fetch_local_market1
from kdutils.macro import base_path
from config.contract import INSTRUMENTS_CODES, INDEX_MAPPING

/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:11: UserWarning: if use distributed calculating, please configure MQ_URL
  warnings.warn('if use distributed calculating, please configure MQ_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:15: UserWarning: if use distributed calculating, please configure NTN_URL
  warnings.warn('if use distributed calculating, please configure NTN_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:19: UserWarning: if use memory database, please configure KN_MG
  warnings.warn('if use memory database, please configure KN_MG')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:27: UserWarning: if use trader, please configure ATL_URL
  warnings.warn('if use trader, please configure ATL_URL')
/workspace/worker/env/lingua/lib/python3.8/site-packages/Finance_Jindowin-1.5.4-py3.8.egg/jdw/__init__.py:31: UserWarning: if use trader, please configure IREY_URL
  warnings.warn('if use trader, please configure IREY_URL')

In [3]:
start_date = '2026-05-06'
end_date = '2026-05-11'
instruments = 'rbb'

cols = ['code','open','high','low','close','volume','value','openint', 'vwap']

In [4]:
data1 = fetch_local_market1(base_path=os.environ['BAR_FUT_DIRS'],
                                       begin_date=start_date,
                                       end_date=end_date,
                                       method=None,
                                       codes=[INSTRUMENTS_CODES[instruments]])
data1

,open,high,low,close,trade_time,volume,value,openint,vwap,code
0,3228.0,3228.0,3219.0,3225.0,2026-05-06 09:00:00,23086.0,744229550.0,1886557.0,NaN,RB
1,3226.0,3229.0,3225.0,3227.0,2026-05-06 09:01:00,11946.0,385548320.0,1889276.0,NaN,RB
2,3227.0,3230.0,3227.0,3230.0,2026-05-06 09:02:00,13570.0,438142360.0,1895028.0,NaN,RB
3,3230.0,3231.0,3229.0,3230.0,2026-05-06 09:03:00,11163.0,360567740.0,1898630.0,NaN,RB
4,3230.0,3230.0,3226.0,3228.0,2026-05-06 09:04:00,6863.0,221515740.0,1898959.0,NaN,RB
...,...,...,...,...,...,...,...,...,...,...
1268,3285.0,3286.0,3285.0,3286.0,2026-05-11 14:56:00,2976.0,97784530.0,2173760.0,3268.0,RB
1269,3286.0,3287.0,3285.0,3286.0,2026-05-11 14:57:00,2351.0,77253500.0,2173640.0,3268.0,RB
1270,3286.0,3286.0,3285.0,3285.0,2026-05-11 14:58:00,2193.0,72046410.0,2173645.0,3268.0,RB
1271,3286.0,3287.0,3285.0,3286.0,2026-05-11 14:59:00,6087.0,199994850.0,2172557.0,3268.0,RB
1272,3286.0,3286.0,3286.0,3286.0,2026-05-11 15:00:00,6.0,197130.0,2172556.0,3268.0,RB

In [5]:
data2 = fetch_main_market(begin_date=start_date,
                                     end_date=end_date,
                                     codes=[INSTRUMENTS_CODES[instruments]],
                                     method=None,
                                     forced_alignment=True)

_cumfactor is not fut_algin_factors column

TypeError: 'NoneType' object is not callable

In [6]:
data1.set_index('trade_time').loc['2026-05-06 10:01:00':][cols].head(10)

,code,open,high,low,close,volume,value,openint,vwap
trade_time,,,,,,,,,
2026-05-06 10:01:00,RB,3895.968321,3897.169668,3894.766974,3897.169668,2848.0,92366150.0,1954661.0,NaN
2026-05-06 10:02:00,RB,3895.968321,3897.169668,3894.766974,3895.968321,875.0,28378690.0,1954804.0,NaN
2026-05-06 10:03:00,RB,3895.968321,3897.169668,3894.766974,3895.968321,1799.0,58343010.0,1954981.0,NaN
2026-05-06 10:04:00,RB,3895.968321,3897.169668,3894.766974,3895.968321,1374.0,44560460.0,1955373.0,NaN
2026-05-06 10:05:00,RB,3897.169668,3898.371015,3895.968321,3895.968321,1957.0,63482030.0,1955785.0,NaN
2026-05-06 10:06:00,RB,3895.968321,3897.169668,3894.766974,3895.968321,1381.0,44781250.0,1955439.0,NaN
2026-05-06 10:07:00,RB,3894.766974,3897.169668,3894.766974,3894.766974,851.0,27595550.0,1955236.0,NaN
2026-05-06 10:08:00,RB,3894.766974,3895.968321,3893.565627,3893.565627,1529.0,49568070.0,1955286.0,NaN
2026-05-06 10:09:00,RB,3894.766974,3895.968321,3893.565627,3894.766974,1315.0,42632920.0,1956031.0,NaN
2026-05-06 10:10:00,RB,3894.766974,3895.968321,3894.766974,3895.968321,769.0,24935160.0,1956367.0,NaN

In [7]:
data2.set_index('trade_time').loc['2026-05-06 10:01:00':][cols].head(10)

,code,open,high,low,close,volume,value,openint,vwap
trade_time,,,,,,,,,
2026-05-06 10:01:00,RB,3895.968321,3897.169668,3894.766974,3895.968321,2850.0,92431010.0,1954661.0,3243.193333
2026-05-06 10:02:00,RB,3895.968321,3897.169668,3894.766974,3895.968321,871.0,28248970.0,1954804.0,3243.280138
2026-05-06 10:03:00,RB,3895.968321,3897.169668,3894.766974,3895.968321,1803.0,58472730.0,1954981.0,3243.079867
2026-05-06 10:04:00,RB,3894.766974,3897.169668,3894.766974,3897.169668,1371.0,44463180.0,1955373.0,3243.120350
2026-05-06 10:05:00,RB,3897.169668,3898.371015,3895.968321,3895.968321,1956.0,63449590.0,1955785.0,3243.844070
2026-05-06 10:06:00,RB,3897.169668,3897.169668,3894.766974,3894.766974,1389.0,45040660.0,1955433.0,3242.668107
2026-05-06 10:07:00,RB,3894.766974,3897.169668,3894.766974,3894.766974,843.0,27336140.0,1955236.0,3242.721234
2026-05-06 10:08:00,RB,3894.766974,3895.968321,3893.565627,3894.766974,1530.0,49600490.0,1955286.0,3241.862092
2026-05-06 10:09:00,RB,3894.766974,3895.968321,3893.565627,3894.766974,1324.0,42924700.0,1956039.0,3242.046828
2026-05-06 10:10:00,RB,3894.766974,3895.968321,3894.766974,3895.968321,764.0,24773110.0,1956369.0,3242.553665